joint_1_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_1

joint_2_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_2

joint_3_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_3

joint_4_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_4

joint_5_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_5

joint_6_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_6

joint_7_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_7

joint_8_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_8

joint_9_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_9

joint_10_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_10

joint_11_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_11

