joint_group_velocity_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5

# Position controller 
joint6_controller:
  type: "position_controllers/JointPositionController"
  joint: joint6


# # Velocity controller 
# joint1_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: joint1

# joint2_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: joint2

# joint3_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: joint3

# joint4_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: joint4

# joint5_controller:
#   type: "velocity_controllers/JointVelocityController"
#   joint: joint5
