joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  # Adjust this value as needed

# Position controllers for the cube
joint_cube_position_controller:
  type: "position_controllers/JointPositionController"
  joint: joint_box





