joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  # Adjust this value as needed

joint_group_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - joint_1
    - joint_2
    - joint_3
    - joint_4
    - joint_5
    - joint_6
    - joint_7
    - joint_8
    - joint_9
    - joint_91
    - joint_92
    - joint_93
    - joint_94
    - joint_95


