# Publish joint_states
rotate_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - joint_1

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50